version: '3.2'
services:
    go-ethereum:
     image: ethereum/client-go
     expose:
      - "8545"
      - "8546"
      - "30303"
      - "30303/udp"
    open-ethereum-pool-pps:
     image: softsky/open-ethereum-pool-pps
     expose:
      - "8080"
      - "8082"
      - "8888"
     environment:
      - MONGO_CONNECTION_STRING=mongo://mongodb:27017/users
      - GOOGLE_AUTH_KEY=${GOOGLE_AUTH_KEY}
     links:
      - go-ethereum
      - mongodb
      - redis  
    redis:
     image: library/redis
     expose:
      - "6379"
    mongodb:
     image: library/mongo
     expose:
      - "27017"
